### ISSUE TITLE
names = ['x','y','tx','ty','allx','ally','adj']分别代表什么？

### ISSUE THREAD

**Issue by dongcy-AHU** [yao8839836/text_gcn#55]
读了你的源码，关于这些矩阵names = ['x','y','tx','ty','allx','ally','adj']分别代表什么？
比如allx => the feature vectors of both labeled and unlabeled training docs/words，你的实验数据不都是有标签的嘛，为什么会有unlabeled training docs？
你在论文中说你的节点初始化为one-hot向量，而我在代码中看到你用word嵌入的平均作为doc嵌入输入，这是为什么？the one-hot labels of the labeled training docs又代表什么？
关于这些x,y,tx,ty等等，我比较难懂，请求您抽出时间为我解答，非常感谢

**Comment by yao8839836** [comment]
@dongcy-AHU 

您好，这几个数据集应该是unlabeled words ，但只要把ally的一部分设为全0，也可以有无标签稳文档。其余几个我的注释应该表明了意思。

我在build_graph.py里是用词向量平均，但后来发现效果不好，于是在train.py里通过这一句features = sp.identity(features.shape[0])  # featureless 将特征向量都变成了one-hot。为了build_graph.py的可扩展和尽量少修改代码，我就没有去掉词向量平均的代码，但实际没有用到。

the one-hot labels of the labeled training docs应该就是y这个矩阵. 假设有三个训练文档，四种类别， 它应该长这样:

[ [0,0,1,0],
 [1,0 ,0, 0],
[0, 0, 0,1] ]

代表每个训练文档是哪个label存在，也就是为1

**Comment by dongcy-AHU** [comment]
@yao8839836 
您好，我将features = sp.identity(features.shape[0])注释掉之后，将自己预训练得到的稠密的向量作为特征向量，运行时出现很多错误，如下，您能帮我看看怎么回事吗？

`Traceback (most recent call last):
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_call
    return fn(*args)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1329, in _run_fn
    status, run_metadata)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot multiply A and B because inner dimension does not match: 28861 vs. 200.  Did you forget a transpose?  Dimensions of A: [28861, 28861).  Dimensions of B: [200,200]
	 [[Node: graphconvolution_1/SparseTensorDenseMatMul/SparseTensorDenseMatMul = SparseTensorDenseMatMul[T=DT_FLOAT, Tindices=DT_INT64, adjoint_a=false, adjoint_b=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_2_0_4, _arg_Placeholder_1_0_3, _arg_Placeholder_0_1, gcn/graphconvolution_1_vars/weights_0/read)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:/text_gcn-master/train.py", line 118, in <module>
    model.layers[0].embedding], feed_dict=feed_dict)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1344, in _do_run
    options, run_metadata)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot multiply A and B because inner dimension does not match: 28861 vs. 200.  Did you forget a transpose?  Dimensions of A: [28861, 28861).  Dimensions of B: [200,200]
	 [[Node: graphconvolution_1/SparseTensorDenseMatMul/SparseTensorDenseMatMul = SparseTensorDenseMatMul[T=DT_FLOAT, Tindices=DT_INT64, adjoint_a=false, adjoint_b=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_2_0_4, _arg_Placeholder_1_0_3, _arg_Placeholder_0_1, gcn/graphconvolution_1_vars/weights_0/read)]]

Caused by op 'graphconvolution_1/SparseTensorDenseMatMul/SparseTensorDenseMatMul', defined at:
  File "G:/text_gcn-master/train.py", line 90, in <module>
    model = model_func(placeholders, input_dim=features[2][1], logging=True)
  File "G:\text_gcn-master\models.py", line 147, in __init__
    self.build()
  File "G:\text_gcn-master\models.py", line 48, in build
    hidden = layer(self.activations[-1])
  File "G:\text_gcn-master\layers.py", line 75, in __call__
    outputs = self._call(inputs)
  File "G:\text_gcn-master\layers.py", line 180, in _call
    support = dot(self.support[i], pre_sup, sparse=True)
  File "G:\text_gcn-master\layers.py", line 33, in dot
    res = tf.sparse_tensor_dense_matmul(x, y)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\sparse_ops.py", line 1795, in sparse_tensor_dense_matmul
    adjoint_b=adjoint_b)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_sparse_ops.py", line 2326, in _sparse_tensor_dense_mat_mul
    name=name)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3160, in create_op
    op_def=op_def)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot multiply A and B because inner dimension does not match: 28861 vs. 200.  Did you forget a transpose?  Dimensions of A: [28861, 28861).  Dimensions of B: [200,200]
	 [[Node: graphconvolution_1/SparseTensorDenseMatMul/SparseTensorDenseMatMul = SparseTensorDenseMatMul[T=DT_FLOAT, Tindices=DT_INT64, adjoint_a=false, adjoint_b=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_2_0_4, _arg_Placeholder_1_0_3, _arg_Placeholder_0_1, gcn/graphconvolution_1_vars/weights_0/read)]]`
